services:
  db:
    build: ./data/db
    
    env_file:
      - ./data/db/.env
    
    ports:
      - "27017:27017"

    volumes:
      - db_data:/data/db

    networks:
      - pipeline

  nginx:
    build: ./nginx

    ports:
      - "80:80"

    depends_on:
      - db

    networks:
      - pipeline
  newman:
    build: ./newman

    volumes:
      - ./newman/collection_tests.json:/app/collection_tests.json
      - ./newman/Environment dnd5e.postman_environment.json:/app/Environment dnd5e.postman_environment.json
      - ./nginx/relatorio_para_testar:/app/reports

    networks:
      - pipeline
      
volumes:
  db_data:

networks:
  pipeline: