services:
  db:
    image: mongo:7
    restart: always
    env_file:
      - ./pipeline_docker/.env
    ports:
      - "27017:27017"
    volumes:
      - ./data/db/init/init.js:/docker-entrypoint-initdb.d/init.js
      - db_data:/data/db
    networks:
      - pipeline

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db
    networks:
      - pipeline

  nginx:
    build:
      context: . 
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - pipeline

  newman:
    build: ./newman
    entrypoint: ["tail", "-f", "/dev/null"] 
    volumes:
      - ./newman:/app/newman
      - ./newman_reports:/app/reports
    networks:
      - pipeline

  jenkins:
    build: ./pipeline_docker
    user: root
    env_file:
      - ./pipeline_docker/.env
    volumes:
      - ./pipeline_docker/jenkins/casc.yaml:/var/jenkins_home/casc_configs/casc.yaml
      - /var/run/docker.sock:/var/run/docker.sock 
      # - .:/var/jenkins_home/workspace/projeto-s07 
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - pipeline
      
volumes:
  db_data:

networks:
  pipeline: