jenkins:
  systemMessage: "Jenkins configurado automaticamente via CasC!"

  numExecutors: 1

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADM_USER}
          password: ${JENKINS_ADM_PASSWORD}

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
- script: >
    pipelineJob('run-jenkinsfile') {
      definition {
        cpsScm {
          scm {
            git {
              remote {
                url('https://github.com/Fefeeu/S07-Testes_API_dnd.git')
              }
              branch('*/main')
            }
          }
          scriptPath('Jenkinsfile')
        }
      }
    }